language: go
go:
  - 1.18.x

install:
  - go install -tags extended github.com/gohugoio/hugo@latest
  
script:
  - mkdir -p themes/beautifulhugo && git clone https://GitHub.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beautifulhugo

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
